name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      run: docker build . --file Dockerfile --tag "${DOCKER_REPO}/alpine/dynamic.lessmore.pw:${GITHUB_SHA}"
    - name: Login
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login --username "${DOCKER_LOGIN}" --password "${DOCKER_PASSWORD}" "${DOCKER_REPO}"
    - name: Push
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      run: docker push "${DOCKER_REPO}/alpine/dynamic.lessmore.pw:${GITHUB_SHA}"
