name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${DOCKER_REPO}/alpine/dynamic.lessmore.pw:${GITHUB_SHA}"
    - name: Login
      run: docker login --username "${DOCKER_LOGIN}" --password "${DOCKER_PASSWORD}" "${DOCKER_REPO}"
    - name: Push
      run: docker push "${DOCKER_REPO}/alpine/dynamic.lessmore.pw:${GITHUB_SHA}"
